[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util.workspace = true
regex = "1.10"
regex-automata = "0.4"
num = "0.4"
ndarray = "0.15"
rayon = "1.8"
